name: Deploy to GitHub Pages with Secrets

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Only needs to read for checkout and sed
      pages: write    # Needs to write to GitHub Pages
      id-token: write # For OIDC token with deploy-pages

    environment: # Important: Define the deployment environment
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace Firebase and Cloudinary Config Placeholders
        run: |
          if [ ! -f index.html ]; then echo "index.html not found!"; exit 1; fi
          sed -i "s|%%FIREBASE_API_KEY%%|${{ secrets.FIREBASE_API_KEY }}|g" index.html
          sed -i "s|%%FIREBASE_AUTH_DOMAIN%%|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" index.html
          sed -i "s|%%FIREBASE_PROJECT_ID%%|${{ secrets.FIREBASE_PROJECT_ID }}|g" index.html
          sed -i "s|%%FIREBASE_DATABASE_URL%%|${{ secrets.FIREBASE_DATABASE_URL }}|g" index.html
          sed -i "s|%%FIREBASE_STORAGE_BUCKET%%|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" index.html
          sed -i "s|%%FIREBASE_MESSAGING_SENDER_ID%%|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" index.html
          sed -i "s|%%FIREBASE_APP_ID%%|${{ secrets.FIREBASE_APP_ID }}|g" index.html
          sed -i "s|%%FIREBASE_MEASUREMENT_ID%%|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" index.html
          sed -i "s|%%CLOUDINARY_CLOUD_NAME%%|${{ secrets.CLOUDINARY_CLOUD_NAME }}|g" index.html
          sed -i "s|%%CLOUDINARY_UPLOAD_PRESET%%|${{ secrets.CLOUDINARY_UPLOAD_PRESET }}|g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository (or specify path to your site's root if different)
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4